spring:
  h2:
    console:
      enabled: true
      path: /db/ui
  datasource:
    url: jdbc:h2:C:/data/db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS event
    driverClassName: org.h2.Driver
    username: test
    password: test
    platform: h2
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update